// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF_T9f0Xri551b_M1Kx5fkDKBBRd2aNDg',
    appId: '1:118199750960:web:a2b88146d3adc3e2f678f5',
    messagingSenderId: '118199750960',
    projectId: 'pond-monitor-ss',
    authDomain: 'pond-monitor-ss.firebaseapp.com',
    databaseURL: 'https://pond-monitor-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pond-monitor-ss.firebasestorage.app',
    measurementId: 'G-XLP32CYSM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNJh5LyABOYHmX4JSJ1U6CHLuI3wXu4m0',
    appId: '1:118199750960:android:7c17ce3342c347dbf678f5',
    messagingSenderId: '118199750960',
    projectId: 'pond-monitor-ss',
    databaseURL: 'https://pond-monitor-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pond-monitor-ss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHlpflHd4w5lCkJrpZi7G26XoESH1N-e4',
    appId: '1:118199750960:ios:9cd2b85891e7d398f678f5',
    messagingSenderId: '118199750960',
    projectId: 'pond-monitor-ss',
    databaseURL: 'https://pond-monitor-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pond-monitor-ss.firebasestorage.app',
    iosBundleId: 'com.example.pondMonitor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHlpflHd4w5lCkJrpZi7G26XoESH1N-e4',
    appId: '1:118199750960:ios:9cd2b85891e7d398f678f5',
    messagingSenderId: '118199750960',
    projectId: 'pond-monitor-ss',
    databaseURL: 'https://pond-monitor-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pond-monitor-ss.firebasestorage.app',
    iosBundleId: 'com.example.pondMonitor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF_T9f0Xri551b_M1Kx5fkDKBBRd2aNDg',
    appId: '1:118199750960:web:5128b618cc5b5002f678f5',
    messagingSenderId: '118199750960',
    projectId: 'pond-monitor-ss',
    authDomain: 'pond-monitor-ss.firebaseapp.com',
    databaseURL: 'https://pond-monitor-ss-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pond-monitor-ss.firebasestorage.app',
    measurementId: 'G-FSBGB4R3JL',
  );

}