name: pond_monitor
description: Pond IoT Monitor
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # --- REQUIRED PACKAGES ---
  firebase_core: ^3.4.0
  firebase_database: ^11.0.3
  google_fonts: ^6.2.1
  intl: ^0.19.0
  fl_chart: ^0.68.0
  # --------------------------

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
